### ISSUE TITLE
Wrong username and/or password

### ISSUE THREAD

**Issue by phidis9** [sumtxt/wiesbaden#4]
**R Code**

`genesis <- c(user="insertuser", password="insertcorrectpassword", db="regio")`
`retrieve_data(tablename="71211-0001", genesis=genesis)`

**Error**
[1] "soapenv:Server.userExceptiongenesis.online.util.exception.XMLGenesisException: Ein Fehler ist aufgetreten. (Bitte prüfen und korrigieren Sie Ihren Nutzernamen bzw.\n das Passwort.)sb2-itd-219.admin.sb2"

**Question**
The username and password are double checked and correct.
Any idea why the function is not working for me as it should?

**Comment by sumtxt** [comment]
I don't know. Seems to be something about user/password combination. Make sure you can login on the website.

**Comment by lauritzst** [comment]
I have the same issue in MATLAB and R. I doube checked and also logged in to the website, which worked. I also created a second account with a new E-Mail and it also worked to log in on the Genesis website, but again, I cannot reach the API via the provided R code or via the webread function in MATLAB.

**Comment by sumtxt** [comment]
Just checked and the [regionalstatistik.de](https://www.regionalstatistik.de/) API is working fine for me. 

`data <- retrieve_data(tablename="14111KJ002", genesis=c(db="regio", user="user", password="password") )`

**Comment by lauritzst** [comment]
I created my account yesterday. Do I have to wait like 24h or should it work immediately? I checked the code on another device and it still does not work. I also tried your code snippet and it also does not work for me. 

The simple "hello world" example in MATLAB works for me
`url = "https://www-genesis.destatis.de/genesisWS/rest/2020/helloworld/whoami";
test = webread(url)`

**Comment by sumtxt** [comment]
Please post the R code you are using and R output you are seeing.

**Comment by lauritzst** [comment]
`# install.packages("wiesbaden")`
`library(wiesbaden)`
`retrieve_data(tablename="14111KJ002", genesis=c(db="regio", user="DE183N3Q27", password="+qrCy=e9J123+"))`
#> [1] "soapenv:Server.userExceptiongenesis.webservice.util.exception.XMLGenesisException: 
#> Ein Fehler ist aufgetreten. (Bitte prüfen und korrigieren Sie Ihren Nutzernamen bzw.
#> \n das Passwort.)idmz-pin1-12107.m00.idmz.nrw.de"`

I plugged in my log-in data in my version, which I do not want to provide. But if this code works for you, I have an issue with my account or log-in data.

**Comment by sumtxt** [comment]
Code is correct and the error messages suggests that the you are connecting to the correct server. Can you confirm that you registered your account via https://www.regionalstatistik.de/ and not via https://www.destatis.de/?

**Comment by lauritzst** [comment]
Apologies for the delayed answer. I texted Genesis and they sent me this:

"Unfortunately there were some problems with the GENESIS-Webservice-Interface (API) yesterday.

If the "logincheck"
<https://www-genesis.destatis.de/genesisWS/rest/2020/helloworld/logincheck?username=YOUR_USERNAME&password=YOUR_PASSWORD&language=en>
displays this message, it is probably due to your password when using the GENESIS-Webservice-Interface. If you use special characters in your password such as ": / ? # [ ] @ ! $ & ' ( ) * + , ; =" etc., these must be expressed as a percentage (url encoding, see: <https://en.wikipedia.org/wiki/Character_encoding>) so that the retrieval works correctly."

This solved my problem. I would keep this here for the future. Some people may run into the same problem.
Many thanks to you @sumtxt :)
